title: My new course
description: This is a test course
template:
  repo: my-new-course-template
  name: my-new-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First lecture
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: Second lecture
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
